apiVersion: app/v1
kind: Deployment
metadata:
  name: goconsumer
spec:
  selector:
    matchlabels:
      app: goconsumer
  template:
    metadata:
      labels:
        app: goconsumer
    spec:
      containers:
      - name: goconsumer
        image: luciano/gointensivo:latest
        ports:
        - containerPort: 8080